{
  "Uuid": "c8db56c4-59ea-4b94-8133-cf3ac447761a",
  "IsCustomNode": false,
  "Description": null,
  "Name": "All Nodes",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.RefineryToolkits.MassingSandbox.Analyze.SiteAnalysis.ClashTest@Autodesk.DesignScript.Geometry.Solid,Autodesk.DesignScript.Geometry.Solid",
      "Id": "810843e2ec1c42fdbbdd4141022116b7",
      "Inputs": [
        {
          "Id": "ff1bd6676b0f423cadb50b6ce9a5c113",
          "Name": "buildingSolid",
          "Description": "Building solid from the generator.\n\nSolid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "22e275da7336493aa1e36946c804476c",
          "Name": "siteSolid",
          "Description": "Site boundary volume.\n\nSolid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2bf9fd42b6514af8847ba253531989e4",
          "Name": "buildingInside",
          "Description": "Volume of building inside of site boundary.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "34a6d5077c4c437ba8709ccfce6f89f0",
          "Name": "buildingOutside",
          "Description": "Volume of building outside of site boundary.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b2b39f5a025943d4a5f2f283429dc90a",
          "Name": "intersects",
          "Description": "Does the building mass intersect with the site boundary?",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "603fdb8c25d745f88249ec935e9161f3",
          "Name": "percentOutside",
          "Description": "Percent of building volume that is outside the site boundary.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Tests site boundary against building mass.\n\nSiteAnalysis.ClashTest (buildingSolid: Solid, siteSolid: Solid): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.RefineryToolkits.MassingSandbox.Analyze.SiteAnalysis.ViewDistance@Autodesk.DesignScript.Geometry.Surface,Autodesk.DesignScript.Geometry.Geometry[],DSCore.Color,DSCore.Color,double,double",
      "Id": "6293a5c255f74acbbdadea12d89d217a",
      "Inputs": [
        {
          "Id": "d36061f018b24de398749afae2eb58ed",
          "Name": "surface",
          "Description": "Surface, such as building's facade, to search from.\n\nSurface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8ff659be937b47718d195b78900b1fe8",
          "Name": "contextGeomList",
          "Description": "Geometry to calculate distance to.\n\nGeometry[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "88e47695fae64ef3823f2d8c9be5e9ee",
          "Name": "startColor",
          "Description": "Color of start of preview color range.\n\nColor\nDefault value : DSCore.Color.ByARGB(255, 255, 0, 115)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "28bde28352404255882bfdd023130d04",
          "Name": "endColor",
          "Description": "Color of end of preview color range.\n\nColor\nDefault value : DSCore.Color.ByARGB(255, 255, 255, 255)",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2343b6ca25834554a95093683e87cafc",
          "Name": "resolution",
          "Description": "Distance between sampling points.\n\ndouble\nDefault value : 3",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0d99391d64814c9c9c9b0643d1bc769e",
          "Name": "maxDistance",
          "Description": "Maximum distance to search.\n\ndouble\nDefault value : 50",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "9f27130d47fe4ce6b59a92c800e98fe3",
          "Name": "pointList",
          "Description": "Sampling points.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "99bae95445064b5e8258cab37b9e0c5f",
          "Name": "distanceList",
          "Description": "Distance from each sampling point along surface normal to the closest context geometry.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fc256489c6994eb08f2e0e6f55e63823",
          "Name": "geometryColor",
          "Description": "Colored surfaces mapping view distance.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Calculates line of sight distances from a grid of points on a surface.\n\nSiteAnalysis.ViewDistance (surface: Surface, contextGeomList: Geometry[], startColor: Color = DSCore.Color.ByARGB(255, 255, 0, 115), endColor: Color = DSCore.Color.ByARGB(255, 255, 255, 255), resolution: double = 3, maxDistance: double = 50): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.RefineryToolkits.MassingSandbox.Generate.Building.ByOutlineArea@Autodesk.DesignScript.Geometry.Curve[],double,double",
      "Id": "1ad272f9f8954c8e97c9f48d6ce6c9df",
      "Inputs": [
        {
          "Id": "8981041ab46e411987bc852967c6c9ed",
          "Name": "edgeLoopCrvList",
          "Description": "Closed curve boundaries of building. All curves after first will be treated as holes.\n\nCurve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "34391396f89245b1b9057448b40b9ef9",
          "Name": "buildingArea",
          "Description": "Target gross building area.\n\ndouble\nDefault value : 10000",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "95d3c13dc3c942ebb7c95d923904d447",
          "Name": "floorHeight",
          "Description": "Height of the floors.\n\ndouble\nDefault value : 3",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "eaf8f3f5321646bc8692759723ec2a81",
          "Name": "buildingSolid",
          "Description": "Building volume.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6688865fd8aa4cc78b9ea565bd72770f",
          "Name": "floorSrfList",
          "Description": "Building floor surfaces.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e2edccf0f5d143169a8e5ad04418c16c",
          "Name": "floorElevationList",
          "Description": "Elevation of each floor in building.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4b20e4cee42a4ba3a58c34f09b181bf3",
          "Name": "topPlane",
          "Description": "A plane at the top of the building volume. Use this for additional volumes to create a stacked building.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "57312cbe22da4c7bb683009b22606fea",
          "Name": "buildingVolume",
          "Description": "Volume of entire building solid.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0dbf9eb231f347a9be4e91146454389f",
          "Name": "grossFloorArea",
          "Description": "Combined area of all floors. Will be at least equal to BldgArea.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "e4bad67893b348a1a79d3922a89e433f",
          "Name": "totalFacadeArea",
          "Description": "Combined area of all facades (vertical surfaces).",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Generates a building solid from base curves and target gross area.\n\nBuilding.ByOutlineArea (edgeLoopCrvList: Curve[], buildingArea: double = 10000, floorHeight: double = 3): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.RefineryToolkits.MassingSandbox.Generate.Building.ByOutlineFloors@Autodesk.DesignScript.Geometry.Curve[],int,double",
      "Id": "67c98801c5904f549a419e9007b22762",
      "Inputs": [
        {
          "Id": "45207614354e407a974301a2e95298fd",
          "Name": "edgeLoopCrvList",
          "Description": "Closed curve boundaries of building. All curves after first will be treated as holes.\n\nCurve[]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "67fa8c693d8947e591a108eae6c772c6",
          "Name": "floorCount",
          "Description": "Target gross building area.\n\nint\nDefault value : 10",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "dfdfc3818ca24e509873d7e067076934",
          "Name": "floorHeight",
          "Description": "Height of the floors.\n\ndouble\nDefault value : 3",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "6c252823b33b495085103d0a12732744",
          "Name": "buildingSolid",
          "Description": "Building volume.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f31c0b70aef14878af1568573f138074",
          "Name": "floorSrfList",
          "Description": "Building floor surfaces.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "623d65b372dc4338af67484748719940",
          "Name": "floorElevationList",
          "Description": "Elevation of each floor in building.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d9d7a7e159a94761837c894eda30000c",
          "Name": "topPlane",
          "Description": "A plane at the top of the building volume. Use this for additional volumes to create a stacked building.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0d623fc947db44fe87feb51b89b3611d",
          "Name": "buildingVolume",
          "Description": "Volume of entire building solid.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3554b17e289e4225abcde1945016ebff",
          "Name": "grossFloorArea",
          "Description": "Combined area of all floors. Will be at least equal to BldgArea.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "eba1030669a14206835a37a7abc595cc",
          "Name": "totalFacadeArea",
          "Description": "Combined area of all facades (vertical surfaces).",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Generates a building solid from base curves and number of floors.\n\nBuilding.ByOutlineFloors (edgeLoopCrvList: Curve[], floorCount: int = 10, floorHeight: double = 3): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.RefineryToolkits.MassingSandbox.Generate.Building.ByTypeArea@Autodesk.DesignScript.Geometry.Plane,string,double,double,double,double,double,bool,bool,double,double,double",
      "Id": "ae1060b17e364f00be5a17d73823f89e",
      "Inputs": [
        {
          "Id": "2c2d5f76fbd44b28be078a773ce8c4f5",
          "Name": "basePlane",
          "Description": "The building base plane.\n\nPlane\nDefault value : Autodesk.DesignScript.Geometry.Plane.XY()",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ce20922d7257471fb5cfe29a0b7fb9a8",
          "Name": "typeStr",
          "Description": "Building type name (\"U\", \"L\", \"H\", \"O\", or \"D\").\n\nstring\nDefault value : \"L\"",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fb43964e68284e3e8423c0bd431e2ef3",
          "Name": "length",
          "Description": "Overall building length.\n\ndouble\nDefault value : 50",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "788ae1a5ec934ec4b90566d554224af0",
          "Name": "width",
          "Description": "Overall building width.\n\ndouble\nDefault value : 40",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "cc9994ef9d2d4e4cb14ef4a0da776064",
          "Name": "depth",
          "Description": "Building depth.\n\ndouble\nDefault value : 25",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a27af6a3106f47cda7c59725718fcea0",
          "Name": "buildingArea",
          "Description": "Target gross building area.\n\ndouble\nDefault value : 10000",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "dedf8cb27f5b4be294013b3d0c2d736e",
          "Name": "floorHeight",
          "Description": "Height of the floors.\n\ndouble\nDefault value : 9",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1f6a1f0cdc6e48989fe21ed1f959cc29",
          "Name": "curvedBool",
          "Description": "Should sides of building be curved or faceted?\n\nbool\nDefault value : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1e39e50503ba452b989ba4f2faf3f4c6",
          "Name": "createCoreBool",
          "Description": "Create core volumes and subtractions?\n\nbool\nDefault value : true",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b6363702b829476196befd9b6e1b2447",
          "Name": "hallwayToDepth",
          "Description": "Core sizing logic: ratio between building depth and width of hallways on either side of core.\n\ndouble\nDefault value : 0.1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ea6b7e310d33458b83c620bfbe4a827e",
          "Name": "coreSizeFactorFloors",
          "Description": "Core sizing logic: Add\n\ndouble\nDefault value : 4",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "009cf4af93c743409cf2594f337cae1b",
          "Name": "coreSizeFactorArea",
          "Description": "Core sizing logic: Add\n\ndouble\nDefault value : 0.1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "e2a5192d7fa34c13b95f88c6cae7511a",
          "Name": "buildingSolid",
          "Description": "Building volume.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5d02739f33d3438bad8e1eacb3cbcdab",
          "Name": "floorSrfList",
          "Description": "Building floor surfaces.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a79d458d1c474247a1cb81d4c23912ec",
          "Name": "netFloorSrfList",
          "Description": "Building floor surfaces with core removed.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3159b73a8d034da6bcfcc5a6b189523a",
          "Name": "floorElevationList",
          "Description": "Elevation of each floor in building.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b7ad09b89a8e4b9fa644dab498b7db08",
          "Name": "coreSolidList",
          "Description": "Building core volumes.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "995d4689e805489b8db52e52a08a3a31",
          "Name": "topPlane",
          "Description": "A plane at the top of the building volume. Use this for additional volumes to create a stacked building.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5eefd04f702f40c7b0fc8616cb8d28aa",
          "Name": "buildingVolume",
          "Description": "Volume of entire building solid.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "44b7bcfd756f4113a854adac3c3b6886",
          "Name": "grossFloorArea",
          "Description": "Combined area of all floors. Will be greater than or equal to input buildingArea.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "17fbccaad5334683b6a9406f3bf4b52e",
          "Name": "netFloorArea",
          "Description": "Combined area of all floors with core removed.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "56bbc75f4b164dbd8a3b9d5b8297f3f6",
          "Name": "totalFacadeArea",
          "Description": "Combined area of all facades (vertical surfaces).",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Generates a building solid by shape type and target gross area.\n\nBuilding.ByTypeArea (basePlane: Plane = Autodesk.DesignScript.Geometry.Plane.XY(), typeStr: string = \"L\", length: double = 50, width: double = 40, depth: double = 25, buildingArea: double = 10000, floorHeight: double = 9, curvedBool: bool = false, createCoreBool: bool = true, hallwayToDepth: double = 0.1, coreSizeFactorFloors: double = 4, coreSizeFactorArea: double = 0.1): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.RefineryToolkits.MassingSandbox.Generate.Building.ByTypeFloors@Autodesk.DesignScript.Geometry.Plane,string,double,double,double,int,double,bool,bool,double,double,double",
      "Id": "61c6a81934ec4f91882e5e0e82f471bd",
      "Inputs": [
        {
          "Id": "de643dfeeae64425849eedce54e1ce38",
          "Name": "basePlane",
          "Description": "The building base plane.\n\nPlane\nDefault value : Autodesk.DesignScript.Geometry.Plane.XY()",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "9b4d1a1eda4d4d50a6f0a0250b55e2f8",
          "Name": "typeStr",
          "Description": "Building type (U, L, H, O, or D).\n\nstring\nDefault value : \"L\"",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b30a8deccbda4c45a1d09a07768672b1",
          "Name": "length",
          "Description": "Overall building length.\n\ndouble\nDefault value : 50",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2cd646c098f04caab35378e3960d6777",
          "Name": "width",
          "Description": "Overall building width.\n\ndouble\nDefault value : 40",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6e02792c7a344186b18add688d4b62e1",
          "Name": "depth",
          "Description": "Building depth.\n\ndouble\nDefault value : 25",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "c72e31093ab64059820b0dbb7aa5d865",
          "Name": "floorCount",
          "Description": "Number of building floors.\n\nint\nDefault value : 10",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "214c7981862c4001b29c6a80938058b0",
          "Name": "floorHeight",
          "Description": "Height of the floors.\n\ndouble\nDefault value : 9",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d433af4840c3412dbbf36e91cbabf427",
          "Name": "curvedBool",
          "Description": "Should sides of building be curved or faceted?\n\nbool\nDefault value : false",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "452c5c11e2af4d9593999cc8d7e76fdb",
          "Name": "createCoreBool",
          "Description": "Create core volumes and subtractions?\n\nbool\nDefault value : true",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0489286a5b034b699b64eb36d3528728",
          "Name": "hallwayToDepth",
          "Description": "Core sizing logic: ratio between building depth and width of hallways on either side of core.\n\ndouble\nDefault value : 0.1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5c22d91848ed4eab9fab23350a80a610",
          "Name": "coreSizeFactorFloors",
          "Description": "Core sizing logic: Add\n\ndouble\nDefault value : 4",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0305edf1818e45e290530f670422008a",
          "Name": "coreSizeFactorArea",
          "Description": "Core sizing logic: Add\n\ndouble\nDefault value : 0.1",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "d4bf976e20074cc3890c0257848ff571",
          "Name": "buildingSolid",
          "Description": "Building volume.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "5e06dafcba0845959884ae764bb810c6",
          "Name": "floorSrfList",
          "Description": "Building floor surfaces.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4e9131b9e7cc4e40964d62f1ddde15ac",
          "Name": "netFloorSrfList",
          "Description": "Building floor surfaces with core removed.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "80cf7eb83ea74b5fb6affdb05e357016",
          "Name": "floorElevationList",
          "Description": "Elevation of each floor in building.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0c93b5b140814ca1b47d0ad6d79c8b69",
          "Name": "coreSolidList",
          "Description": "Building core volumes.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "80cc525073b3408fa4aa3fead18056eb",
          "Name": "topPlane",
          "Description": "A plane at the top of the building volume. Use this for additional volumes to create a stacked building.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "3f68f352bda14a2eb10ef0ef0a35bc73",
          "Name": "buildingVolume",
          "Description": "Volume of entire building solid.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4e1b61ba9ea34f3fb252f03232ad9ee8",
          "Name": "grossFloorArea",
          "Description": "Combined area of all floors. Will be at least equal to BldgArea.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d83567b7ef7b4479adfa4327c124f6ab",
          "Name": "netFloorArea",
          "Description": "Combined area of all floors with core removed.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "24496fb10f15461ebbb44b25a511f14e",
          "Name": "totalFacadeArea",
          "Description": "Combined area of all facades (vertical surfaces).",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Generates a building solid by shape type and number of floors.\n\nBuilding.ByTypeFloors (basePlane: Plane = Autodesk.DesignScript.Geometry.Plane.XY(), typeStr: string = \"L\", length: double = 50, width: double = 40, depth: double = 25, floorCount: int = 10, floorHeight: double = 9, curvedBool: bool = false, createCoreBool: bool = true, hallwayToDepth: double = 0.1, coreSizeFactorFloors: double = 4, coreSizeFactorArea: double = 0.1): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.RefineryToolkits.MassingSandbox.Generate.Building.GetSurfaceLoops@Autodesk.DesignScript.Geometry.Surface",
      "Id": "ae7b3823ba8c41b3a1e33d8a2dafee2e",
      "Inputs": [
        {
          "Id": "82d91cf95de543769de7e02fa682eb8f",
          "Name": "surface",
          "Description": "The surface.\n\nSurface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "42cfea143c7243c8b92b7cde307c7ed8",
          "Name": "edgeCrvList",
          "Description": "Edges of surface.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Gets a list of closed polycurve edges of surface. First list item is outside boundary.\n\nBuilding.GetSurfaceLoops (surface: Surface): PolyCurve[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.RefineryToolkits.MassingSandbox.Generate.Building.SelectBuildingType@int",
      "Id": "71285bafe1174756a54cf8cf09a3a93c",
      "Inputs": [
        {
          "Id": "5ced5dc56013463180b4905df9e672dc",
          "Name": "shapeIndex",
          "Description": "Index of building type to select from list of possible types.\n\nint\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "403db26d49384842aa99c993f9b706fe",
          "Name": "buildingTypeStr",
          "Description": "Name of building type. One of \"U\", \"L\", \"H\", \"O\", or \"D\".",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Uses an integer index to select a building type letter from the list of possible options (\"U\", \"L\", \"H\", \"O\", or \"D\").\n\nBuilding.SelectBuildingType (shapeIndex: int = 0): string"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.RefineryToolkits.MassingSandbox.Generate.Building.DeconstructFacadeShell@Autodesk.DesignScript.Geometry.Topology,double",
      "Id": "c51d21567d7040ea9e08faa998d9d9ce",
      "Inputs": [
        {
          "Id": "b3e82614acd541c5a080f986be1d47e6",
          "Name": "solid",
          "Description": "Building solid.\n\nTopology",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2ae17dbcd40d498583638d3c80441b80",
          "Name": "angleThreshold",
          "Description": "Threshold for classification. 0 (more vertical surfaces) - 90 (more horizontal surfaces).\n\ndouble\nDefault value : 45",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "2dd551d49ea049b5b9aeb314a5ac434e",
          "Name": "verticalSrfList",
          "Description": "Vertical surfaces.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b7aeeaf8b5304e1384f792e5ba32753b",
          "Name": "horizontalSrfList",
          "Description": "Horizontal surfaces.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Deconstructs a building solid into component horizontal and vertical surfaces.\n\nBuilding.DeconstructFacadeShell (solid: Topology, angleThreshold: double = 45): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.RefineryToolkits.MassingSandbox.Generate.Site.VolumeByOutlineSetback@Autodesk.DesignScript.Geometry.Curve,double,double",
      "Id": "44739082dd3440b48bcca3ae559a5a57",
      "Inputs": [
        {
          "Id": "d56234a3d9f442d6be9d406cdc0290d6",
          "Name": "siteOutline",
          "Description": "Site boundary, from Revit.\n\nCurve",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "01d68d8c310b4421968eda6975be5916",
          "Name": "setback",
          "Description": "Site setback distance.\n\ndouble\nDefault value : 0",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "1c39549cb6b04f1da0172d4247c92e96",
          "Name": "heightLimit",
          "Description": "Maximum building height.\n\ndouble\nDefault value : 100",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "04a3100a4ef8433d97ee5069d42ebe01",
          "Name": "siteSolid",
          "Description": "Allowable volume for building mass.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f46375c4183d423a9914dff9fffe9d5f",
          "Name": "siteOffset",
          "Description": "Allowable footprint for building mass.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Uses setback and height to create boundary volume for building solid to fit into.\n\nSite.VolumeByOutlineSetback (siteOutline: Curve, setback: double = 0, heightLimit: double = 100): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.RefineryToolkits.MassingSandbox.Generate.Site.ContextByElement@Autodesk.DesignScript.Geometry.PolySurface",
      "Id": "834dd7317b1b4b25b5c84f05280bca87",
      "Inputs": [
        {
          "Id": "b2840a3ee77b451aa85fcd7735f18c75",
          "Name": "polysurface",
          "Description": "Referenced site element.\n\nPolySurface",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "f5dfadf3f45741399d769df82f8f35f4",
          "Name": "solidList",
          "Description": "Individual solids in site geometry.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "50cd4a24ebfa4948b2e4078cdb61497d",
          "Name": "boundingBoxList",
          "Description": "Bounding box for each element.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "8b743c9a418843289fe697a55bd38a28",
          "Name": "heightList",
          "Description": "Height of each element.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Gets site components from polysurface (e.g. Revit mass).\n\nSite.ContextByElement (polysurface: PolySurface): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.RefineryToolkits.MassingRevit.Integrate.Revit.CreateRevitFloors@Autodesk.DesignScript.Geometry.Surface[][],Revit.Elements.FloorType,string",
      "Id": "8c1ea3b6f2dc4e0d94706ba17adb77f4",
      "Inputs": [
        {
          "Id": "7cb9bd1180444563833eed85fefed699",
          "Name": "srfList",
          "Description": "Floor surfaces.\n\nSurface[][]",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b393e2c8675f48209c260f13b3c34cf4",
          "Name": "floorType",
          "Description": "Type of created Revit floors.\n\nFloorType",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "4f3e787be94747eeb306477f3cf3016c",
          "Name": "levelPrefixStr",
          "Description": "Prefix for names of created Revit levels.\n\nstring\nDefault value : \"Dynamo Level\"",
          "UsingDefaultValue": true,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "eda452e16e62499c8d6f083a4a8dde44",
          "Name": "floorElementList",
          "Description": "Revit floor elements.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates Revit floors from building floor surfaces.\n\nRevit.CreateRevitFloors (srfList: Surface[][], floorType: FloorType, levelPrefixStr: string = \"Dynamo Level\"): Floor[][]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.RefineryToolkits.MassingRevit.Integrate.Revit.CreateRevitMass@Autodesk.DesignScript.Geometry.Solid,Revit.Elements.Category",
      "Id": "c7debbba0329414ea1c483e45802747f",
      "Inputs": [
        {
          "Id": "aaaef18eb5144695a79bf6d2ab2ff0ef",
          "Name": "BuildingSolid",
          "Description": "The building volume.\n\nSolid",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "eddd474e92224888ba3965b29e3fbe1b",
          "Name": "Category",
          "Description": "A category for the mass.\n\nCategory",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b892392a9cd84934854a110a58244869",
          "Name": "RevitBuilding",
          "Description": "Revit DirectShape element.",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Creates a Revit mass as a direct shape.\n\nRevit.CreateRevitMass (BuildingSolid: Solid, Category: Category): DirectShape"
    }
  ],
  "Connectors": [],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.2.6826",
      "RunType": "Automatic",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -61.883405592369158,
      "EyeY": -123.849057147049,
      "EyeZ": 253.89057494421192,
      "LookX": 46.078487259051663,
      "LookY": -49.918361197305963,
      "LookZ": -222.71268841874965,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "ShowGeometry": true,
        "Name": "SiteAnalysis.ClashTest",
        "Id": "810843e2ec1c42fdbbdd4141022116b7",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 956.8775749235067,
        "Y": 897.996600653974
      },
      {
        "ShowGeometry": true,
        "Name": "SiteAnalysis.ViewDistance",
        "Id": "6293a5c255f74acbbdadea12d89d217a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1696.0298817523624,
        "Y": 902.18974123415592
      },
      {
        "ShowGeometry": true,
        "Name": "Building.ByOutlineArea",
        "Id": "1ad272f9f8954c8e97c9f48d6ce6c9df",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 634.30142150907886,
        "Y": 92.142595742420156
      },
      {
        "ShowGeometry": true,
        "Name": "Building.ByOutlineFloors",
        "Id": "67c98801c5904f549a419e9007b22762",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 999.772681273525,
        "Y": 92.1425957424202
      },
      {
        "ShowGeometry": true,
        "Name": "Building.ByTypeArea",
        "Id": "ae1060b17e364f00be5a17d73823f89e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1369.6759828958848,
        "Y": 92.142595742420156
      },
      {
        "ShowGeometry": true,
        "Name": "Building.ByTypeFloors",
        "Id": "61c6a81934ec4f91882e5e0e82f471bd",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1762.3632635892877,
        "Y": 92.142595742420156
      },
      {
        "ShowGeometry": true,
        "Name": "Building.GetSurfaceLoops",
        "Id": "ae7b3823ba8c41b3a1e33d8a2dafee2e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2155.0505442826907,
        "Y": 92.142595742420156
      },
      {
        "ShowGeometry": true,
        "Name": "Building.SelectBuildingType",
        "Id": "71285bafe1174756a54cf8cf09a3a93c",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2432.7378249760936,
        "Y": 92.142595742420156
      },
      {
        "ShowGeometry": true,
        "Name": "Building.DeconstructFacadeShell",
        "Id": "c51d21567d7040ea9e08faa998d9d9ce",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 2759.4251056694966,
        "Y": 92.142595742420156
      },
      {
        "ShowGeometry": true,
        "Name": "Site.VolumeByOutlineSetback",
        "Id": "44739082dd3440b48bcca3ae559a5a57",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 634.30142150907886,
        "Y": 902.18974123415592
      },
      {
        "ShowGeometry": true,
        "Name": "Site.ContextByElement",
        "Id": "834dd7317b1b4b25b5c84f05280bca87",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1327.4537283379345,
        "Y": 902.18974123415592
      },
      {
        "ShowGeometry": true,
        "Name": "Revit.CreateRevitFloors",
        "Id": "8c1ea3b6f2dc4e0d94706ba17adb77f4",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 991.33818988124017,
        "Y": 623.53241087386766
      },
      {
        "ShowGeometry": true,
        "Name": "Revit.CreateRevitMass",
        "Id": "c7debbba0329414ea1c483e45802747f",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 625.866930116794,
        "Y": 623.53241087386732
      }
    ],
    "Annotations": [],
    "X": 95.920690075643677,
    "Y": 264.82120530660649,
    "Zoom": 0.31534856480613305
  }
}