<Workspace Version="1.3.4.6666" X="-731.42693421875" Y="-219.14960721875" zoom="1.545620359375" ScaleFactor="1" Name="Isolated Pick Model Elements" Description="This allows a multiple selection of elements of specified category." ID="9dba20d5-ee3a-4fad-ae88-9b859fff9cb7" Category="Rhythm.Revit.Selection.Selection">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="39383be9-f43a-49c2-b423-a6dbac345bda" type="PythonNodeModels.PythonNode" nickname="Python Script" x="1123.2768838658" y="353.012371778627" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="2">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <Script>#Copyright(c) 2017, john pierson
# @60secondrevit, http://sixtysecondrevit.com
#Sometimes a pick selection is better
#Based on a node from Dimitar Venkov

import clr

clr.AddReference("RevitAPIUI")
from  Autodesk.Revit.UI import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
TaskDialog.Show('Isolated Selection','Pick elements of category, ' + (IN[1].lower()) + '. Press finish to complete.')

sel1 = uidoc.Selection
obt1 = Selection.ObjectType.Element
class CustomISelectionFilter(Selection.ISelectionFilter):
	def __init__(self, nom_categorie):
		self.nom_categorie = nom_categorie
	def AllowElement(self, e):
		if e.Category.Name == self.nom_categorie:
			return True
		else:
			return False
	def AllowReference(self, ref, point):
		return true
		
el_ref = sel1.PickObjects(obt1, CustomISelectionFilter(IN[1]), 'Pick elements of category, ' + (IN[1].lower()) + ' Press finish to complete.')
typelist = list()
idlist = list()
for i in el_ref:
	
	try:
		typelist.append(doc.GetElement(i.ElementId))
	except:
		typelist.apped(list())
		

OUT = typelist</Script>
    </PythonNodeModels.PythonNode>
    <CoreNodeModels.FromObject guid="eea510e1-622d-4c6a-bf7d-1f421c038c72" type="CoreNodeModels.FromObject" nickname="String from Object" x="906.276883865796" y="407.012371778627" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
    </CoreNodeModels.FromObject>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="0995d374-1e34-4027-bd14-c1e6d1f40c60" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="776.276883865796" y="303.012371778627" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="refresh : bool = false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="9abb2dc0-66b1-494f-8fc6-8d11631c4695" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="708.276883865796" y="407.012371778627" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="category" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="d87e5922-70e9-4593-abb9-2de8f020721f" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1347.2768838658" y="352.012371778627" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="elements" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="39383be9-f43a-49c2-b423-a6dbac345bda" start_index="0" end="d87e5922-70e9-4593-abb9-2de8f020721f" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="eea510e1-622d-4c6a-bf7d-1f421c038c72" start_index="0" end="39383be9-f43a-49c2-b423-a6dbac345bda" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="0995d374-1e34-4027-bd14-c1e6d1f40c60" start_index="0" end="39383be9-f43a-49c2-b423-a6dbac345bda" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="9abb2dc0-66b1-494f-8fc6-8d11631c4695" start_index="0" end="eea510e1-622d-4c6a-bf7d-1f421c038c72" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>