<Workspace Version="1.3.2.2480" X="-79.4872444685475" Y="-132.317734594261" zoom="0.931811528498331" ScaleFactor="1" Name="UI.ColorPicker" Description="This node allows the user to choose a color via the Revit API color selection dialog. For Revit 2017 +" ID="b730bbbe-8c54-4ce0-bbfb-2ab4d1ece3ae" Category="Rhythm.Revit.UI">
  <NamespaceResolutionMap>
    <ClassMap partialName="DSCore.Color" resolvedName="DSCore.Color" assemblyName="DSCoreNodes.dll" />
  </NamespaceResolutionMap>
  <Elements>
    <PythonNodeModels.PythonNode guid="8ddeca5e-d12f-475e-9c9f-ed4f185f4936" type="PythonNodeModels.PythonNode" nickname="Python Script" x="828.433045356371" y="509.04016974383" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" inputcount="1">
      <PortInfo index="0" default="False" />
      <Script>#Copyright(c) 2017, john pierson
# @60secondrevit, http://sixtysecondrevit.com
import clr
import msvcrt

clr.AddReference("RevitAPIUI")
from  Autodesk.Revit.UI import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
doc = DocumentManager.Instance.CurrentDBDocument
uidoc=DocumentManager.Instance.CurrentUIApplication.ActiveUIDocument

clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)
#Custom flatten definition to manage lists in here
def flatten(*args):
    for x in args:
        if hasattr(x, '__iter__'):
            for y in flatten(*x):
                yield y
        else:
            yield x
#Constructs the window
window = ColorSelectionDialog()
#Allows the window to popup
selected = ColorSelectionDialog.Show(window)
#Gets the selected color
userColor = window.SelectedColor
#Special thanks to andreas Dieckmann for this code.
rlist = list()
glist = list()
blist = list()
rlist.append(userColor.Red)
glist.append(userColor.Green)
blist.append(userColor.Blue)

OUT = userColor,flatten(rlist,glist,blist)
</Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="1e867fb0-347c-4c5d-a630-87a7a9a0d8bd" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1050.43304535637" y="555.253503077163" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="true" CodeText="DSCore.Color.ByARGB(255,seq[1][0],seq[1][1],seq[1][2]);" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="140ef04e-ab2f-426c-a082-e8ea3e06b831" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="475.459009540478" y="499.083294385814" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="//toggle with boolean to refresh&#xD;&#xA;refresh : bool =false" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="def0a1c6-a70d-4374-bb2c-9c5dc20811b8" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1668.43304535637" y="467.04016974383" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="revitColor" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
    <Dynamo.Graph.Nodes.CodeBlockNodeModel guid="7860627b-c89f-4173-8ecb-a0dbeb2c3b59" type="Dynamo.Graph.Nodes.CodeBlockNodeModel" nickname="Code Block" x="1050.43304535637" y="471.253503077163" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" CodeText="x[0];" ShouldFocus="false">
      <PortInfo index="0" default="False" />
    </Dynamo.Graph.Nodes.CodeBlockNodeModel>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="b73343d9-aeea-4a2a-9d67-cff21df713a0" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="1668.43304535637" y="551.04016974383" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="dynamoColor" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="8ddeca5e-d12f-475e-9c9f-ed4f185f4936" start_index="0" end="1e867fb0-347c-4c5d-a630-87a7a9a0d8bd" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="8ddeca5e-d12f-475e-9c9f-ed4f185f4936" start_index="0" end="7860627b-c89f-4173-8ecb-a0dbeb2c3b59" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="1e867fb0-347c-4c5d-a630-87a7a9a0d8bd" start_index="0" end="b73343d9-aeea-4a2a-9d67-cff21df713a0" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="140ef04e-ab2f-426c-a082-e8ea3e06b831" start_index="0" end="8ddeca5e-d12f-475e-9c9f-ed4f185f4936" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="7860627b-c89f-4173-8ecb-a0dbeb2c3b59" start_index="0" end="def0a1c6-a70d-4374-bb2c-9c5dc20811b8" end_index="0" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
</Workspace>